### ISSUE TITLE
Dropbox 110.4.458 fails to start on CentOS 7.9

### ISSUE THREAD

**Issue by nmusatti** [flathub/com.dropbox.Client#191]
From /var/log/messages:
Nov 28 12:52:47 imladris com.dropbox.Client.desktop: dropbox: locating interpreter
Nov 28 12:52:47 imladris com.dropbox.Client.desktop: dropbox: logging to /tmp/dropbox-antifreeze-y2fVLJ
Nov 28 12:52:47 imladris com.dropbox.Client.desktop: dropbox: initializing
Nov 28 12:52:47 imladris com.dropbox.Client.desktop: dropbox: initializing python 3.7.9
Nov 28 12:52:47 imladris com.dropbox.Client.desktop: dropbox: setting program path '/app/extra/.dropbox-dist/dropbox-lnx.x86_64-110.4.458/dropbox'
Nov 28 12:52:47 imladris com.dropbox.Client.desktop: dropbox: setting python path '/app/extra/.dropbox-dist/dropbox-lnx.x86_64-110.4.458:/app/extra/.dropbox-dist/dropbox-lnx.x86_64-110.4.458/python-packages.zip'
Nov 28 12:52:47 imladris com.dropbox.Client.desktop: dropbox: python initialized
Nov 28 12:52:47 imladris com.dropbox.Client.desktop: dropbox: running dropbox
Nov 28 12:52:47 imladris com.dropbox.Client.desktop: dropbox: setting args
Nov 28 12:52:47 imladris com.dropbox.Client.desktop: dropbox: enabling allocator metrics
Nov 28 12:52:47 imladris com.dropbox.Client.desktop: dropbox: applying overrides
Nov 28 12:52:47 imladris com.dropbox.Client.desktop: dropbox: running main script
Nov 28 12:52:47 imladris com.dropbox.Client.desktop: dropbox: load fq extension '/app/extra/.dropbox-dist/dropbox-lnx.x86_64-110.4.458/cryptography.hazmat.bindings._constant_time.cpython-37m-x86_64-linux-gnu.so'
Nov 28 12:52:47 imladris com.dropbox.Client.desktop: dropbox: load fq extension '/app/extra/.dropbox-dist/dropbox-lnx.x86_64-110.4.458/cryptography.hazmat.bindings._openssl.cpython-37m-x86_64-linux-gnu.so'
Nov 28 12:52:47 imladris com.dropbox.Client.desktop: dropbox: load fq extension '/app/extra/.dropbox-dist/dropbox-lnx.x86_64-110.4.458/cryptography.hazmat.bindings._padding.cpython-37m-x86_64-linux-gnu.so'
Nov 28 12:52:48 imladris com.dropbox.Client.desktop: dropbox: load fq extension '/app/extra/.dropbox-dist/dropbox-lnx.x86_64-110.4.458/psutil._psutil_linux.cpython-37m-x86_64-linux-gnu.so'
Nov 28 12:52:48 imladris com.dropbox.Client.desktop: dropbox: load fq extension '/app/extra/.dropbox-dist/dropbox-lnx.x86_64-110.4.458/psutil._psutil_posix.cpython-37m-x86_64-linux-gnu.so'
Nov 28 12:52:48 imladris com.dropbox.Client.desktop: dropbox: load fq extension '/app/extra/.dropbox-dist/dropbox-lnx.x86_64-110.4.458/apex._apex.cpython-37m-x86_64-linux-gnu.so'
Nov 28 12:52:48 imladris com.dropbox.Client.desktop: dropbox: load fq extension '/app/extra/.dropbox-dist/dropbox-lnx.x86_64-110.4.458/tornado.speedups.cpython-37m-x86_64-linux-gnu.so'
Nov 28 12:52:49 imladris com.dropbox.Client.desktop: dropbox: load fq extension '/app/extra/.dropbox-dist/dropbox-lnx.x86_64-110.4.458/wrapt._wrappers.cpython-37m-x86_64-linux-gnu.so'
Nov 28 12:52:50 imladris com.dropbox.Client.desktop: dropbox: load fq extension '/app/extra/.dropbox-dist/dropbox-lnx.x86_64-110.4.458/PyQt5.QtWidgets.cpython-37m-x86_64-linux-gnu.so'
Nov 28 12:52:50 imladris com.dropbox.Client.desktop: Traceback (most recent call last):
Nov 28 12:52:50 imladris com.dropbox.Client.desktop: File "dropbox/client/main.pyc", line 503, in <module>
Nov 28 12:52:50 imladris com.dropbox.Client.desktop: File "dropbox/foundation/navigation_service/factory.pyc", line 22, in <module>
Nov 28 12:52:50 imladris com.dropbox.Client.desktop: File "dropbox/foundation/navigation_service/navigation_service_impl.pyc", line 51, in <module>
Nov 28 12:52:50 imladris com.dropbox.Client.desktop: File "dropbox/foundation/html_views/electron/manager_factory.pyc", line 14, in <module>
Nov 28 12:52:50 imladris com.dropbox.Client.desktop: File "dropbox/foundation/html_views/local/common/manager.pyc", line 33, in <module>
Nov 28 12:52:50 imladris com.dropbox.Client.desktop: File "dropbox/client/features/model_registry.pyc", line 13, in <module>
Nov 28 12:52:50 imladris com.dropbox.Client.desktop: File "dropbox/client/features/generated_models.pyc", line 315, in <module>
Nov 28 12:52:50 imladris com.dropbox.Client.desktop: File "dropbox/client/features/previews/view_anchor.pyc", line 106, in <module>
Nov 28 12:52:50 imladris com.dropbox.Client.desktop: File "<_bootstrap_overrides>", line 153, in load_module
Nov 28 12:52:50 imladris com.dropbox.Client.desktop: ImportError: libglapi.so.0: cannot open shared object file: No such file or directory
Nov 28 12:52:50 imladris com.dropbox.Client.desktop: !! dropbox: fatal python exception:
Nov 28 12:52:50 imladris com.dropbox.Client.desktop: ['Traceback (most recent call last):\n', '  File "dropbox/client/main.pyc", line 503, in <module>\n', '  File "dropbox/foundation/navigation_service/factory.pyc", line 22, in <module>\n', '  File "dropbox/foundation/navigation_service/navigation_service_impl.pyc", line 51, in <module>\n', '  File "dropbox/foundation/html_views/electron/manager_factory.pyc", line 14, in <module>\n', '  File "dropbox/foundation/html_views/local/common/manager.pyc", line 33, in <module>\n', '  File "dropbox/client/features/model_registry.pyc", line 13, in <module>\n', '  File "dropbox/client/features/generated_models.pyc", line 315, in <module>\n', '  File "dropbox/client/features/previews/view_anchor.pyc", line 106, in <module>\n', '  File "<_bootstrap_overrides>", line 153, in load_module\n', 'ImportError: libglapi.so.0: cannot open shared object file: No such file or directory\n'] (error 3)

**Comment by nmusatti** [comment]
Fixed by #192
